package com.example.zuut;

public class Constants {
    public static final String BIRD = "Bird";
    public static final String VOI = "Voi";
    public static final String ZUUT = "Zuut";
    public static final int ZOOM_VALUE = 17;
    public static final int BEARING_VALUE = 90;
    public static final int TILT_VALUE = 40;
    public static final String PERCENT = "%";
    public static final int DURATION_VALUE = 750;
    public static final int I = 100;
    public static final int BATTERY_MAX_LEVEL = 100;
    public static final int ESTIMATED_RANGE_VALUE = 1000;
    public static final String EMAIL = "email";
    public static final String TOKEN = "token";
    public static final String ACCESS = "access";
    public static final String REFRESH = "refresh";
    public static final String LOCATION = "location";
    public static final String LATITUDE = "latitude";
    public static final String BATTERY_LEVEL = "battery_level";
    public static final String ESTIMATED_RANGE = "estimated_range";
    public static final String BIRDS = "birds";
    public static final String TOKEN_ACTIVITY = "TokenActivity";
    public static final String REGISTER_ACTIVITY = "RegisterActivity";
    public static final String TEST = "Test";
    public static final String JSON_PARSING_FAILED = "Json parsing failed";
    public static final String CODE = "code";
    public static final String AUTHENTICATION_TOKEN = "authenticationToken";
    public static final String ACCESS_TOKEN = "accessToken";
    public static final String X_ACCESS_TOKEN = "x-access-token";
    public static final String ZONES = "zones";
    public static final String ZONE = "zone";
    public static final String PHONE_NUMBER = "phone_number";
    public static final String COUNTRY_CODE = "country_code";
    public static final String AUTH_TOKEN = "authToken";
    public static final String DATA = "data";
    public static final String VEHICLE_GROUPS = "vehicle_groups";
    public static final String VEHICLES = "vehicles";
    public static final String BATTERY = "battery";
    public static final String ID = "id";
    public static final String ZONE_ID = "zone_id";
    public static final String LAT = "lat";
    public static final String LNG = "lng";
    public static final String LONGITUDE = "longitude";
    public static final String VOI_VERIFY_PHONE_ACTIVITY = "VoiVerifyPhoneActivity";
    public static final String REGISTER_FAILED = "Register Failed";
    public static final String VOI_PHONE_ACTIVITY = "VoiPhoneActivity";

}
